export const environments = {
    baseUrl: 'http://localhost:8080/',
    register: 'register',
    login: 'login',
        logout: 'auth/logout',
    emailConfirmation: 'email-confirmation',
    resetPassword: 'reset-password',
    forgotPassword: 'forgot-password',
    profileFetch: 'profile-fetch',
    getCategories: 'categories',
    ticketUrl: 'tickets/',
    addTicket: 'add',
    getTickets: '',
    getStatus: 'status',
    getChart: 'chart',
    adminUrl: 'admin/',
    getUsersList: 'get-users-list',
    rolesUrl: 'roles/',
    getAllRoles: 'get-all',
    assignRole: 'assign',
    removeRole: 'remove',
    updateDescrpition: '/description',
    updateStatus: '/statuschange',

    notificationUrl: 'notifications/',
        markAsRead: '/read',
        getPending: '/pending',
        getAlreadyRead: '/already-read',

    wsUrl: ''
}