export const enviroments = {
    baseUrl: 'http://localhost:8080/',
    register: 'register',
    login: 'login',
    emailConfirmation: 'email-confirmation',
    resetPassword: 'reset-password',
    forgotPassword: 'forgot-password',
    profileFetch: 'profile-fetch',
    getCategories: 'categories',
    getTicketById: 'ticket/${id}',
    ticketUrl: 'tickets/',
    addTicket: 'add',
    getTickets: '',
    getStatus: 'status',
    getChart: 'chart',
    adminUrl: 'admin/',
    getUsersList: 'get-users-list',
    rolesUrl: 'roles/',
    getAllRoles: 'get-all',
    assignRole: 'assign',
    removeRole: 'remove'
}